### ISSUE TITLE
Could not run flutter driver on iOS simulator

### ISSUE THREAD

**Issue by lucastien** [jonsamwell/flutter_gherkin#100]
I was struggled with running flutter driver test with flutter_gherkin support on iOS simulator. The test was corrupted after running the command ``flutter drive --target=test_driver/app.dart`` . On Android, it run successfully.
![Screen Shot 2020-12-06 at 22 53 12](https://user-images.githubusercontent.com/5175237/101285244-b7432900-3816-11eb-9ab3-73184f85851b.png)

Could you please check my crash report log for futher detail of error? Thanks
[flutter_01.log](https://github.com/jonsamwell/flutter_gherkin/files/5649062/flutter_01.log)

**Comment by jonsamwell** [comment]
@lucastien Looks like a problem with Flutter itself.  I suggest you file a bug with the Flutter team something is going wrong in the file `flutter_tools/src/ios/simulators.dart`.

It you use the latest stable channel do you still get the error?

I suggest you also upgate your POD file as per the build warning message.

Also you should be running flutter_gherkin using the dart command line rather than flutter driver i.e.

```dart test_driver/app.dart```

Closing for now as it appears a Flutter bug
