### ISSUE TITLE
Step function for dragging

### ISSUE THREAD

**Issue by LSG-6** [jonsamwell/flutter_gherkin#113]
With given2 method, we can write a step function for clicking a button for n times, but how can I write a step function for dragging in a specific direction on the gestrueDectector?

**Comment by jonsamwell** [comment]
You would just do this the normal way you would do it with the flutter driver apis.

Note this is easier using the new `WidgetTester` as it has a drag method.  

Once the migration to using the integration_test package and subsequently using WidgetTester instead of flutter driver is complete the drag operation will be easier

The migration is pretty much working and I am using it successfully on two huge apps and it is working well, more reliable and quicker. Feel free to take a look as the code is pretty stable. I just need to find time to update the documentation around it and I will be updating this library.

Branch: https://github.com/jonsamwell/flutter_gherkin/tree/integration_test__package_support
Issue: #101
