### ISSUE TITLE
Is it possible to inspect the state of the app?

### ISSUE THREAD

**Issue by esDotDev** [jonsamwell/flutter_gherkin#129]
We would like to somehow read the state of the application to verify it's behavior. For example, checking the current `userModel.session != null` after logging in.

Is this possible?

**Comment by jonsamwell** [comment]
@esDotDev sorry for the delayed reply here.

In short yes although it isn't the easiest with flutter_driver (I assume in part why the Flutter team now reccommend using WidgetTester).

Basically you need to start a debugging session in your app (with the enableDriver extension method invoked) then you can tell the tests to run against that running instance of the app rather than an instance it starts up.  You will then be debugging the app while the tests run against it.  See https://github.com/jonsamwell/flutter_gherkin#debugging

However, if you have a small test project (even if you don't) I would highly recommend looking at and migrating to the 3.0.0-rc1 version of this library which has first class support for the WidgetTester (intergration_test pacakge) way of doing things.  Debugging state of the app during tests is as simple as debugging the tests as the tests surround the app and do not connect to an isolated instance of it like flutter driver tests do.  See https://pub.dev/packages/flutter_gherkin/versions/3.0.0-rc.1.  The documentation is a bit spare on that version but the code works very well (using it on two huge projects).  Once I get time to do detailed documentation I'll promote this to the main library and slowly depricate the flutter_driver way of doing things
