### ISSUE TITLE
Generate json with JsonReporter when some test fail

### ISSUE THREAD

**Issue by jamontes79** [jonsamwell/flutter_gherkin#170]
Using flutter_gherkin 3.0.0-rc.7 when some test fails, the json generated by JsonReporter is not generated. It would be important to know which test are failing when we use automatic process to run them.

integration_test_driver.dart
`
import 'package:integration_test/integration_test_driver.dart'
    as integration_test_driver;

Future<void> main() {
  // The Gherkin report data send back to this runner by the app after
  // the tests have run will be saved to this directory
  integration_test_driver.testOutputsDirectory =
      'integration_test/gherkin/reports';

  return integration_test_driver.integrationDriver(
    timeout: Duration(minutes: 90),
  );
}
`

gherkin_suite_test.dart
`
part 'gherkin_suite_test.g.dart';

@GherkinTestSuite()
void main() {
  executeTestSuite(
    FlutterTestConfiguration.DEFAULT(
      [
        
      ],
    )
      ..reporters = [
        JsonReporter(
          writeReport: (_, __) => Future<void>.value(),
        ),
      ],
    (World world) async {
      await getIt.reset();
      app.main();
    },
  );
}
`

Thanks a lot in advance

**Comment by AFASbart** [comment]
Yes so I also had this problem. I hope that @jonsamwell wants to fix this. It is in the integration_test_driver.dart function integrationDriver() it has an if statement:

`if (response.allTestsPassed) {
    print('All tests passed.');
    if (responseDataCallback != null) {
      await responseDataCallback(response.data);
    }
    exit(0);
  } else {
    print('Failure Details:\n${response.formattedFailureDetails}');
    exit(1);
  }`

I think everyone can figure out why your results aren't being saved haha

So Jon you going to continue to do this, because I believe saving a report should happen all the time.

**Comment by AFASbart** [comment]
I just saw this is from an external package and @jonsamwell cannot do anything about it. What I have done is copied the function that you return in your own integration_test_driver.dart and placed it in my own file. Removed the if statement and created my own writeGherkinReports function (you don't have to, but I think the other way is stupid, due to no version control).

If you want to I can send you my version if you want to.

**Comment by jamontes79** [comment]
> I just saw this is from an external package and @jonsamwell cannot do anything about it. What I have done is copied the function that you return in your own integration_test_driver.dart and placed it in my own file. Removed the if statement and created my own writeGherkinReports function (you don't have to, but I think the other way is stupid, due to no version control).
> 
> If you want to I can send you my version if you want to.

Yes please, it would be very helpful for me. 
Thanks in advance

**Comment by AFASbart** [comment]
I have removed some parts of the code, that is because these are secrets of the project I am working on.
But what you'll need will be present.

Sooo my integration_test_driver.dart has this as the main function:
# Main function
```
Future<void> main() async {
  // The Gherkin report data send back to this runner by the app after
  // the tests have run will be saved to this directory
  driverLog = logDriverMessages;
  integration_test_driver.testOutputsDirectory = 'integration_test/reports';

  return integrationDriver(
    timeout: const Duration(minutes: 90),
  );
}
```

# integrationDriver (Return function)
```
Future<void> integrationDriver({
  Duration timeout = const Duration(minutes: 20),
}) async {
  final FlutterDriver driver = await FlutterDriver.connect();
  final String jsonResult = await driver.requestData(null, timeout: timeout);
  final Response response = Response.fromJson(jsonResult);

  await driver.close();

  final now = DateTime.now();
  final reports = json.decode(response.data!['gherkin_reports'].toString())
      as List<dynamic>;

  await writeGherkinReports(reports, now);

  exit(0);
}
```

# writeGherkinReports
```
Future<void> writeGherkinReports(
    List<dynamic> reports, DateTime currentTime) async {
  //For each report we are going to save the json file.
  for (var i = 0; i < reports.length; i += 1) {
    final reportData = reports.elementAt(i) as List<dynamic>;

    //create the directory if it does not exist.
    await fs
        .directory(integration_test_driver.testOutputsDirectory)
        .create(recursive: true);

    final version = reports.length == 1 ? "" : "_v${i + 1}";

    //The filename of the report
    final fileName =
        "${currentTime.day}-${currentTime.month}-${currentTime.year}T${currentTime.hour}_${currentTime.minute}$version.json";

    //Creating the file object to save the data in.
    final File file = fs.file(path.join(
      integration_test_driver.testOutputsDirectory,
      fileName,
    ));

    //Encoding the List<dynamic> to a stringified JSON object.
    final String resultString = _encodeJson(reportData, true);

    //Saving the stringified JSON object into a .json file.
    await file.writeAsString(resultString);
  }
}
```

This is it. Make sure all the functions are correctly referenced (some functions have the same name so double check everything)

**Comment by jamontes79** [comment]
> _encodeJson

Thanks a lot!! Works like a charm :)

I'm going to mantain the issue open to check if it would be possible to have this fix in the library

**Comment by jonsamwell** [comment]
@jamontes79 it would be good to file a bug with flutter for this one but I will add some documentation and this function to the library for now.

**Comment by AFASbart** [comment]
I have updated it with the _encodeJson, forgot that one wasn't in the original file..

**Comment by colleenvillon** [comment]
This is really a big help! thank you so much @AFASbart

**Comment by colleenvillon** [comment]
@AFASbart @jonsamwell  How can we add test logs (exceptions) of failed test step on the json file? thank you

**Comment by jonsamwell** [comment]
Closing as the example project now includes code to deal with this
