### ISSUE TITLE
Bypass Permissions (Push Notifications)

### ISSUE THREAD

**Issue by mozes-pb** [jonsamwell/flutter_gherkin#27]
Hi @jonsamwell ,
Do you know how to bypass permissions like push notifications and other system alert message when running the test?

Thanks.

**Comment by jonsamwell** [comment]
Sorry I don't know how to do this.  It is a question you could post on Stackoverflow or the Flutter driver issues github page.

**Comment by bartonhammond** [comment]
In case someone else finds this....
I did the following.  I wrote a script that uninstalls the app (thus resetting all the permissions) and then grants all permissions.  My tests run on iOS and do not deal w/ permission prompts 
```
xcrun simctl uninstall CA0BCD8D-1EB0-4DFD-B452-BDA42C313C9A online.myfamilyvoice.mobile
xcrun simctl privacy CA0BCD8D-1EB0-4DFD-B452-BDA42C313C9A grant all online.myfamilyvoice.mobile
flutter clean
flutter run -d CA0BCD8D-1EB0-4DFD-B452-BDA42C313C9A -t lib/main_integration_test.dart --verbose
```

**Comment by bartonhammond** [comment]
Now that we can run the Features by sorted filename (`..order = ExecutionOrder.sorted`), I put the tests that encounter Permissions at the beginning and I manually OK them by using `And I pause for 10 seconds`.  I start the server with the following script so that I know the first time through the Permissions will pop up due to the `uninstall`.  It's brute force but it works for me.
```
xcrun simctl uninstall CA0BCD8D-1EB0-4DFD-B452-BDA42C313C9A online.myfamilyvoice.mobile
flutter clean
flutter run -d CA0BCD8D-1EB0-4DFD-B452-BDA42C313C9A -t lib/main_integration_test.dart --verbose
```
