### ISSUE TITLE
onAfterScenarioWorldCreated called after onBeforeScenario

### ISSUE THREAD

**Issue by russell-sf** [jonsamwell/flutter_gherkin#42]
I need to install some isolate extensions before my scenarios are run so that they can call back to flutter code. I need the world to do this so I can get at the flutter driver and its isolate.

I was hoping to do this with onAfterScenarioWorldCreated as it is passed the world and I assumed it was called before any scenario callbacks were called. Apparently onBeforeScenario is called first but it doesn't get passed the world object. I need the isolate extensions in place before onBeforeScenario is called.

Thoughts?

**Comment by jonsamwell** [comment]
Hi russell-sf,

Yes I see your problem here.  One possible solution would be to create your own world object that extends the FlutterWorld (https://github.com/jonsamwell/flutter_gherkin/blob/master/lib/src/flutter/flutter_world.dart#L6).  You could then override the `setFlutterDriver` method (ensure you call super.setFlutterDriver(driver)) first.  At that point no steps have run and the flutter driver has just been created so you could setup the extensions at that point.

The good thing with this solution is that you also get a handle on when the flutter driver is closed so you can do any clean etc in the `dispose` method.

```
class CustomTestWorld extends FlutterWorld {
  @override setFlutterDriver(FlutterDriver driver) {
    super.setFlutterDriver(driver);
    // init extensions here
  }

  @override
  void dispose() {
    super.dispose();
    // cleanup code...
  }
}
```

**Comment by russell-sf** [comment]
Thanks Jon! Interesting idea but its still calling onBeforeScenario before my world is even created.

The relavant code is actually in gherkin at
 https://github.com/jonsamwell/dart_gherkin/blob/0f39a739a4829182620e780866ed652f7d5ed4dc/lib/src/feature_file_runner.dart#L110-L118

Can onBeforeScenario be moved to after the following if block?

**Comment by jonsamwell** [comment]
Sorry for the late reply, I'll sort this out for you.

**Comment by jonsamwell** [comment]
@russell-sf I've moved the `onBeforeScenario` to after the world creation so you will have access to the world in this method if you save an as an instance member when the `onAfterScenarioWorldCreated` is called.  Let me know how you get on.
