### ISSUE TITLE
How to correctly work with Given steps?

### ISSUE THREAD

**Issue by dustin-graham** [jonsamwell/flutter_gherkin#9]
@jonsamwell question for you. I'm working on implementing steps for the following scenario for a feature in my app called "paperless shop":

```gherkin
  Scenario: User cannot use paperless shop without permissions
    Given that the User does not have permissions to paperless shop
    When the User views the menu options
    Then the User does not see paperless shop.
```

I'm new to gherkin and BDD so please provide me correction to my understanding if needed, but I'm struggling to find a way to fulfill the Given scenario displayed above. The intent here is that of a "set up" step. Given the following from the Gherkin language spec, I think it's an appropriate statement:

[Given](https://docs.cucumber.io/gherkin/reference/#given)
`Given steps are used to describe the initial context of the system - the scene of the scenario. It is typically something that happened in the past.`

However, by the time my given step runs my application is already started and running and my opportunity to put the system in a specific state for the test is very limited. Owing to this, I think the example project suffers from the same dilemma I'm currently facing:

[Example Given](https://github.com/jonsamwell/flutter_gherkin/blob/master/example/test_driver/steps/given_I_pick_a_colour_step.dart)
```dart
class GivenIPickAColour extends Given1<Colour> {
  @override
  Future<void> executeStep(Colour input1) async {
    print("The picked colour was: '$input1'");
  }

  @override
  RegExp get pattern => RegExp(r"I pick the colour {colour}");
}
```
The step simply prints out and does nothing, but then again, how would this step influence the "initial context of the system" now that the system is already running?

A further evidence that I think we have something missing here is in the [drawer.feature](https://github.com/jonsamwell/flutter_gherkin/blob/master/example/test_driver/features/drawer.feature)
```dart
Feature: Drawer

  Scenario: should open the drawer
    Given I open the drawer
    Given I close the drawer
```

The Gherkin spec also advises in the Given step: `The purpose of Given steps is to put the system in a known state before the user (or external system) starts interacting with the system (in the When steps). Avoid talking about user interaction in Given’s. If you were creating use cases, Given’s would be your preconditions.` the example of `I open the drawer` feels inappropriate for a Given step.

My initial thoughts on how to achieve this are similar to what I did to start my mock web server and provide my url to the running app via `requestData` and an await in the main method of my app. Since my step has access to the created `driver`, I could perhaps send data to the running app and have my app instrumented to wait for specific Given instructions.

This would certainly give me the opportunity to do something, but what can be done with such a primitive interface like `requestData`? If I'm limited to sending just a string, I could send a request to execute a pre-arranged command in the host app. To make this effective though, We'd need the ability to write code that runs on the device that can perform work on the test runner's behalf. It would do things like writing values to shared preferences and databases.

Today I'm going to try and prototype something along these lines. I'd like your feedback on these thoughts and ideas though.

Thanks!

**Comment by dustin-graham** [comment]
@jonsamwell  So far here's what I'm thinking we should do:

1. Expand the base step definitions to allow implementations to provide a "pre-run" command that maps to a "native step".
2. The "native step" is a simple class that gets called on the device when the step dispatched the pre-run command.
3. Before `runApp` is called, the user can await the completion all the "pre-run" "native step" steps to finish. All the native steps are run in the order that their steps appear in the feature file.
4. Once all the pre-run native steps are completed, the app then can call `runApp` to continue on with the test.

One of my considerations in this design is the fact that a feature file's preconditions can be broken up between a given and zero or more And and But steps. Additionally, the presence of Background steps with their own Given,And,But steps complicates things. We can't just have one "configure" event for the scenario. Each precondition step needs to have some say into how the running environment is configured for the test, but the app still needs to get running in order for the other steps to execute successfully. So I think that by gathering together any of the steps that require preconditions and dispatching those all up front is the best I've come up with so far.

**Comment by jonsamwell** [comment]
Hi @dustin-graham ,

Just a quick response as I am out at the moment I will written a more details response later.

Work to setup the app so that the test starts from the correct point should be done in the 'Background' section imho but many people might have different thoughts @paul-hammant would probably have a good opinion here?

This is the standard way of setting things up in BDD world.  For instance if you app needs to test a feature where a new user has logged in the background steps would be something like:

```
Background
  Given a new user has registered
  And logged in

Scenario: new user can add a todo
  Given the user is on the todo page
  And the user clicks on the "add todo" button
  Then they can add a new todo item
  ..........
  ..........
```

Note that there is no hard and fast rule about using Given in both the Background and Feature sections

I tend to take the approach that the background steps are implemented using API calls so in the above context the background steps would use an api to create a new user, and basically correctly setup the data.  This data would then be stored in the world object that the steps in the scenrio section can access (in the above example maybe a username or some other information).  It seems to me that needing code within the app to setup the testing is an anti-pattern as the test should be independent of platform (in pure BDD sense although the reality will always be slightly different).

So if you need to setup preferences data etc it should be done using the steps you have already implemented to test that functionality in the Background section.  Although I can see your point here to want to skip this bit and do it in code as it would be much quicker.

I'll pull out an example of a more complex test we are using for an app when I get home.  However, we have a test envirnoment so we do not need to mock any data as I recall you are?

I can see the advantages of a native step but it does feel odd to have code to setup and application for test in the application itself.

Perhaps you could setup a simple repo of what you want to achieve and we can both work through it and use it as a bit of a better sample.  That way we can see if we need to extends this repo a bit more.

One of things I really want to do soon rather than latter is split out the Gherkin part of the repo so this is a Flutter implemenation of the top of the base Gherkin library.  Although one for another day.

Actually this was a rather long reply! Haha.

Let me know what you think.

Thanks for using the library by the way!

Jon

**Comment by dustin-graham** [comment]
@jonsamwell Thanks. You've given me a lot of food for thought. I'll take some more time to think. 

One point you highlighted in your description of how you use the Background section is that there is really 2 types of work that needs to be done when running these tests. First and most obvious is interacting with the device directly via the FlutterDriver: tapping, scrolling, getting text, etc. The second, less obvious kind, is environment setup work. You hit an API to create a user for your test and put important bits of information in the World object so you can use that info to drive your test (I suspect username and password for the login screen?). In my case I have a test API too, it's just an ad-hoc server I have running in the DartVM next to my executing integration test on my host machine. I can send it commands and configure it to do what I need as well. For the sake of discussion I'd like to give these two modes of work different names so they are easy to talk about: direct work, and meta work. Direct work being work that is done with device interactions via the FlutterDriver and Meta Work is work that is done by other means with the purpose of influencing the operating environment to behave in predictable ways for other parts of the test.

With that distinction in place, I can see that a good portion of my meta work can be done by controlling my mock api server to respond in certain ways. In fact, in the case I pasted above I will need to tell my mock API to return a user object with specific permissions missing. However, I do believe there is other meta work that is best done by directly influencing the app on the device.

I think it would be valuable for discussion if I provided a better example of a test situation that may need to run code on the device to accomplish the test effectively:

Our app uses an OAuth system where the login system is not controlled by our own API. We use Auth0 with AzureAD. Our login page isn't owned by us, its a webview where the user logs in with their Active Directory credentials and we end up with an auth token passed back to our app via a method channel. In this case it's pretty much impossible for me to control login from FlutterDriver directly. The only way I can my my tests work is for the device to think its already logged in by having its auth token already setup in secure storage. So I've got to run some flutter code to make that happen.

In addition to the AuthToken, the identity provider also passes back an IdToken which contains user information in it. These things often need to be injected on a per-scenario basis in order for the test to work correctly.
--
However, considering your advice, I will say that it seems the best practice to make a majority of the tests use direct work rather than meta work. Additionally, meta work should not be used as a short cut to accomplish things that can be reasonably done with normal interactions with the application.

**Comment by jonsamwell** [comment]
@dustin-graham how you getting on?

**Comment by dustin-graham** [comment]
Pretty good. I avoided the need for this functionality for now by prepping
my data for the scenario ahead of time and plugging it into my mock server.

**Comment by jonsamwell** [comment]
Awesome!

**Comment by paul-hammant** [comment]
I like the idea of having a mock service allow you to fast forward to the thing you're trying to test. @dustin-graham which tech are you using for a mock server/service ?

Also `Given the user is on the todo page` implies "logged in & reg'd" and is just fine for me as it is (with no context/background lines in the same scenario/feature.

**Comment by dustin-graham** [comment]
I'm using this package and having good success with it.
https://pub.dartlang.org/packages/mock_web_server

I may write up a blog post on how to use it in conjunction with this
package. But I have a pattern setup so that I can declare a data response
co figuration easily for all my scenarios and I have a hook which can
automatically select the predefined scenario given the provided scenario
name. I was also able to set it up so that I could run it during
interactive development too.
