### ISSUE TITLE
exitAfterTestRun = false is not respected

### ISSUE THREAD

**Issue by vrnvorona** [jonsamwell/flutter_gherkin#90]
1. Create app
2. in config get exitAfterTestRun = false
3. Write some steps, implement them
4. Run test with dart test_driver/app_test.dart
5. Wait for steps to pass
Expected: After all steps finish, app remains in state it finished
Actual: After all steps finish, app closes with stdout "Terminating Flutter app under test"

When steps fail, app is not closed, but is restarted with "Restarting Flutter app under test"

It would be quite helpful to let app stay as it is to inspect how it ended, currently you need to watch app run to debug it, which may make you to skip accidentally moment of crash/bug/fail in tests. This can be avoided by screenshotting/recording, but it's not really comfortable to do so.

I would look why it's not behaving as expected (though i may be wrong in expected behavior), but i am not fluid with Dart yet.

**Comment by jonsamwell** [comment]
Thanks for reporting this I'll look into it.  I think the problem comes if a test fails part way through a test run and the last test to run did not fail.  Regardless, I'll try and make it respect the flag.

See link below with info on how to add a hook to capture a screenshot on failure:

https://github.com/jonsamwell/flutter_simple_dependency_injection/blob/master/test/flutter_simple_dependency_injection_test.dart#L199

**Comment by vrnvorona** [comment]
Thanks for tip on screenshot.

In my case all tests were green, then app would close. If it would fail - it would restart. I didn't test multiple scenarios, maybe it is a problem (i run only one scenario currently to check things out)
